dataset:
  # data_path: C:\Users\test\Desktop\Leon\Datasets\Snoring_Detection\Snoring Dataset
  # index_path: C:\Users\test\Downloads\0930\model_test2
  # index_path: C:\Users\test\Desktop\Leon\Datasets\ASUS_snoring_subset\index\ASUS_snoring
  index_path: C:\Users\test\Desktop\Leon\Datasets\ASUS_snoring_subset\index\ASUS_Kaggle_train_ASUS_test
  index_path: C:\Users\test\Desktop\Leon\Datasets\ASUS_snoring_subset\index\ASUS_Kaggle_16k_train_ASUS_test
  data_split: 
    - 0.7
    - 0.3
  sample_rate: 16000
  transform_methods:
    - MFCC
  transform_config:
    n_fft: 1024
    win_length: null
    hop_length: null
    n_mels: 128
    n_mfcc: 128
  fuse_method: mean
  batch_size: 14
  shuffle: True
  is_data_augmentation: True
  preprocess_config:
    is_freq_masking: True
    is_time_masking: True
    is_time_strech: False 
    freq_mask_param: 80
    time_mask_param: 80
    min_rate: 0.9
    max_rate: 1.1
# use a fixed random seed to guarantee that when you run the code twice you will get the same outcome
manual_seed: 0
# model configuration
model:
  # model class, e.g. UNet3D, ResidualUNet3D
  name: resnet50
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 2
  # determines the order of operators in a single layer (gcr - GroupNorm+Conv3d+ReLU)
  # layer_order: gcr
  # feature maps scale factor
  # f_maps: 32
  # number of groups in the groupnorm
  # num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1 convolution, otherwise apply nn.Softmax
  activation: null
  # if True applies the final normalization layer (sigmoid or softmax), otherwise the networks returns the output from the final convolution layer; use False for regression problems, e.g. de-noising
  # is_segmentation: true
  output_strides: 16
  pretrained: True

# training configuration
train:
  loss: CrossEntropy
  optimizer: Adam
  epoch: 300
  learning_rate: 0.0000005
  project_path: C:\Users\test\Desktop\Leon\Projects\Snoring_Detection
  checkpoint_saving_steps: 50
